apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: document-service
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  lifecycle: dev
  owner: team-platform
  system: permis360-backend
  tags:
    - backend
    - java
    - spring-boot
    - microservices
  dependsOn:
    - component:sdk-common