
spring:
  mvc:
    apiversion:
      use:
        header: api-version
      default: v1.0
      supported:
        - v1.0
        - v2.0
  docker:
    compose:
      enabled: false
      file: /Users/errabi/Desktop/projects/autoecole-platform/docker-compose.yaml
  application:
    name: school-service
  cloud:
    openfeign:
      oauth2:
        enabled : true
        clientRegistrationId: keycloak
  security:
    oauth2:
      resourceserver: # Resource Server Configuration used to validate incoming JWT tokens
        jwt:
          issuer-uri: http://keycloak-service:8080/realms/api-core
      client: # OAuth2 Client Configuration used for outgoing requests
        registration:
          keycloak:
            client-id: siyaka-client
            scope: openid,profile,email
            client-secret: isCfVzXZDfsNiyo5HiKpfkFlg7bV3cGS
            authorization-grant-type: client_credentials
        provider:
          keycloak:
            issuer-uri: http://keycloak-service:8080/realms/api-core
  # H2 Database Configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/autoecole_db?currentSchema=school
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        default_schema: school
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: false
    locations: classpath:db/migration
    baseline-on-migrate: true
  # Enable H2 Console (optional, for development/testing)
  h2:
    console:
      enabled: true
      path: /h2-console
  data:
    redis:
      host: redis-service
      port: 6379

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui/index.html
    oauth:
      client-id: siyaka-client
      client-secret: RgxUa9qvjDXXbs5MsnH7vUqnszoye0bI

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: school-service
      environment: staging
server:
  port: 8080

api-core:
  document-service:
    url : http://document-service:8080

keycloak:
  server-url: http://keycloak-service:8080
  realm: master
  client-id: admin-cli
  target-realm: api-core
  target-client: siyaka-client
  client-secret: "Gvl0g8mXguprYFegYONxLaIvvWnGdEaL"

app :
  cache:
    expiration-time : 10 # 10 Minutes