
spring:
  mvc:
    apiversion:
      use:
        header: api-version
      default: v1.0
      supported:
        - v1.0
        - v2.0
  docker:
    compose:
      enabled: true
      lifecycle-management: start_and_stop
      file: ./docker-compose-dev.yaml
  application:
    name: school-service
  cloud:
    openfeign:
      oauth2:
        enabled : true
        clientRegistrationId: keycloak
  security:
    oauth2:
      resourceserver: # Resource Server Configuration used to validate incoming JWT tokens
        jwt:
          issuer-uri: http://localhost:8080/realms/api-core
      client: # OAuth2 Client Configuration used for outgoing requests
        registration:
          keycloak:
            client-id: siyaka-client
            scope: openid,profile,email
            client-secret: isCfVzXZDfsNiyo5HiKpfkFlg7bV3cGS
            authorization-grant-type: client_credentials
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/api-core
  # H2 Database Configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/autoecole_db?currentSchema=school
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        default_schema: school
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    default-schema: school
    schemas: school
    locations: classpath:db/migration
  h2:
    console:
      enabled: false
      path: /h2-console
  data:
    redis:
      host: localhost
      port: 6379

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui/index.html
    oauth:
      client-id: siyaka-client
      client-secret: RgxUa9qvjDXXbs5MsnH7vUqnszoye0bI

management:
  endpoints:
    web:
      exposure:
        include: health,metrics
  health:
    circuitbreakers:
      enabled: true
server:
  port: 8081

api-core:
  document-service:
    url : http://localhost:8009

keycloak:
  server-url: http://localhost:8080
  realm: master
  client-id: admin-cli
  target-realm: api-core
  target-client: siyaka-client
  client-secret: "Gvl0g8mXguprYFegYONxLaIvvWnGdEaL"

app :
  cache:
    enabled: false
    expiration-time : 10 # 10 Minutes

resilience4j:
  circuitbreaker:
    instances:
      documentService:
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10              # Tracks the outcome of the last 10 calls
        minimumNumberOfCalls: 5            # Minimum calls needed before calculating the failure rate
        failureRateThreshold: 50           # Opens the circuit if 50% or more of calls fail
        waitDurationInOpenState: 10s       # Time to wait before testing recovery (Half-Open state)
        permittedNumberOfCallsInHalfOpenState: 3 # Number of test calls allowed in Half-Open state