
keycloak-url=http://194.163.129.95:8080
keycloak-realm=api-core
keycloak-issuer-uri = http://194.163.129.95:8080/realms/api-core
keycloak-client-id=siyaka-client
keycloak-client-secret=isCfVzXZDfsNiyo5HiKpfkFlg7bV3cGS
keycloak-admin-cli-secret=I6v8bQBorTZz0VzSDVpihpjkvQ7DdUbO


postgres-url=jdbc:postgresql://194.163.129.95:5432/autoecole_db?currentSchema=school
postgres-username=admin
postgres-password=admin
postgres-schema-name=school
redis-host=194.163.129.95

document-service-url = http://194.163.129.95:8009

redis-cache-enabled= false
redis-cache-ttl=10

eureka-server-url=http://eureka-service:8080/eureka/