
keycloak-url=http://keycloak-service/auth
keycloak-realm=api-core
keycloak-issuer-uri = http://keycloak-service/auth/realms/api-core
keycloak-client-id=siyaka-client
keycloak-client-secret=tH3KulwiHm2BUuOP1Dyy9JMlYRRvSC97
keycloak-admin-cli-secret=1d26wNlaTn7Vck3VrP60pa9SjRCbMd52


postgres-url=jdbc:postgresql://postgres-service:5432/autoecole_db?currentSchema=school
postgres-username=
postgres-password=
postgres-schema-name=school
redis-host=redis-service

document-service-url = http://document-service:8080

redis-cache-enabled= false
redis-cache-ttl=10