apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: postgres-vs
  namespace: staging
spec:
  hosts:
    - postgres.external.db
  gateways:
    - mesh
    - istio-system/istio-egressgateway
  tcp:
    # App → Egress Gateway
    - match:
        - gateways:
            - mesh
          port: 5432
      route:
        - destination:
            host: istio-egressgateway.istio-system.svc.cluster.local
            subset: postgres
            port:
              number: 5432
    # Egress Gateway → External IP
    - match:
        - gateways:
            - istio-system/istio-egressgateway
          port: 5432
      route:
        - destination:
            host: 194.163.129.95
            port:
              number: 5432