apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: postgres-vs
  namespace: staging
spec:
  hosts:
    - postgres.external.db
  gateways:
    - mesh
    - istio-system/istio-egressgateway
  tcp:
    # 1. App → Egress Gateway
    - match:
        - gateways:
            - mesh
          port: 5432
      route:
        - destination:
            host: istio-egressgateway.istio-system.svc.cluster.local
            subset: postgres
            port:
              number: 5432
    # 2. Egress Gateway → External PostgreSQL
    - match:
        - gateways:
            - istio-system/istio-egressgateway
          port: 5432
      route:
        - destination:
            host: postgres.external.db
            port:
              number: 5432