apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-auth-secret
  namespace: staging
spec:
  encryptedData:
    root-password: AgCfQq2ImQNAtJdSeOW5peE/Yhl1XbY/mrYJcct4lBJEjSfFy7jF7U4SwuPiFiMIybvGq5wi0gGaJksBDUiX8X8bBENZoxVJ4LucI85VyCggaYqDnxCXiY0RmWs4/uL8YPCRIcfcP4efr5jPxN0yYNXB+iLB9CiB5ISshuElgi76ZG6KTA1NS8DT3h4lBMOzORhmKaZJNqTCLtBG3u890z3r6OL38TfsZK+YFYVck95yrblUc4QHoAY6JZk6ebidJ7OvYjJPcQCuzISRXtfkjCIxGDxQgrUt9zKmwO2cLG+oNGdMJ2eRYxhSwE6XrjZLOvAxrX3eIw1rBxxQg5dXiHId/g+s5/nmpUtlQ1Tjj/sUVGaMJvd8OBeRoeWGj0XHloYRDCQ8PBG0JD7HJNOQ6GvKxsG3DnvrEBUDDrJZVcV5H7ZkBOgqSUEvK2j0i9BbI0On6BeGMIp1mKYdN71pTL3qW47FP6zdUABqeiuwMMHglvvpB/8R0mo634cZbFVUwBLLzRnEbAbCSuaYP3F3OBeI+ScNfnvBRMa7gJW5GhtFwCCq2gcXNgvitWVxQoN+GXuny5jbebpJueufYEyhMkm9MmPWXBk3OPphdKQFFT4n61+cAeptRU8Ng7jY2tmIPyeXbGF5bWhH5S3icxBdzJ5WVFVh3wLHxsZC5QgSL7En9+t7BKSPeAP18KY4nBGaaEXDZgV3/gdYNaOA
    root-user: AgAPeWsItRf1wBv67ZsNF5JeTiTv2PwZAkcg99J+CybLY/9QckB074F8P42YDFjIARfsYfN1C3HQu2Go6CKNO78wXs33TYCK1GhozduMNJ+rbBE7GmtKagGaoEl+AZXpzr9pG4mmkIGTrMTc3RwF/eaUW/kojhsQ54ZtG2RGT6J1CtGuv9qP277/HYYLv9B6+0rkO+f0TCr2NUTyAvE71Hsjq3WyRi6FGHA+ZOSLXRig7SjoWcG0MDn3qJl9J7Y0aqu0x2h3F7VuTqJhf6xaH07aE9zGkxnEFWQ3OwSSJmtmWhEwPWMzjxMLxlf1Zl2061KCrQxzPGODKNfyxdAizNUuVS9/3l4TDqgh/LtmNgvqFI7TUzJx5Zc9Ydv00hrXZcui7H6P4wHsJiKXXmnbJ+tnRnbovOySri83sp2e8iwSXWRgVN/GzmoqmHJ1w4yImitYZ5R35/UojnGJF1V/EafZxtN1kQLrx564vO3sdhWtTcLveDGGRUlxwJ0qnT+zZyaZwsaZEX1aEFA/DlzXFKhrheA+xm2swdUexTrdgwC8eW5n/KYaJ/QSwtOAnBQPFwuJiXOjv2V8TBuFHLbkh/yvDgD914JXIYtZaY7Mp1+HRdpgMRaXjyW1GdiJXlm+Op/F0gAZTonCadJj8GQH1EMf3WMphjPynZHTB5IO/V9GezlPuHEKgHW3qYAALAl6M/67KzKypj1OII33
  template:
    metadata:
      name: minio-auth-secret
      namespace: staging
    type: Opaque
