apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: keycloak-credentials
  namespace: staging
spec:
  encryptedData:
    admin-password: AgC1KMTkGss90JQh/iApVidwZrmidHzPCvROfCAQCT8zMnpPF+ntSKmX3sjwQTJZoUfHAC4D0pjBPSCgsdWpocC7OddNt5PcDcVYeP5P0M1MOcIzlhXgeaUVoGv0LL8IzyusRpSMA0Get3WPuJ39Ki/jpVqlA96kH7SMKf+Xgc9KGCweSt8HCXsaENChpvVvmkiRfXbpdVRq+iOHzOXAU8Kjg6iayHAlWJavReuvxC9V8Dw4TPHStucig+H6GaFvpbeKxvW3LDoOCkeLiQUpo/Vcxm5lnrjTz2UFGCSLAm1U+8P31++ez+u3dlXRWu0y3K8zf2EiqWZPLamu7p0+gUdOumUpE52TvNnkxR6/bL05eJrKkvGJO/Oe+s3uVjT2Ztp8/3omzCMA8xzSY7U+IJj5tsQ4Ufq4fg+NlRmwzEOqy9vJcllLAMagVQv6yGZ3IXJLE2qHZ8hnk57N9wr/oYhM23UZbTCUi19gold1qrFQlg7tf193YpiN8HJF8g6KS+NInrxB6rKH4kxXZE5wz1gdtIDYm6qUxuyGHMziyx8twbvn9J4oy6pXBXxQgROT5RybhayB/Er4t5+A4isrOFzS2SWqJ6ctNEd0jSIgSZQflmRCMD+gWgu2kC8ck/euSri84dCIiahV3Fgz5fFdMVfbQZV1l2ppuWt/lTqQYygJDL4KHtWJLwKYuzyApGiIsUAu+fT4Gw==
    admin-user: AgAn5g+snPZE1mAF1VeoIBfSgZFZeoNzNwTdqJoy+b4p1a0+nyAoITzIH4ma9kH8EaN/BUEa1XhfB1Z+nQ351XZZl9YZeitpbfbF2UBaGqUHw7ke9gFO81tTSTeUzL9hyppv/96PNKNv4x2q/O7Z9/5EcHCJA6tBnzWOAScM5SNug6Qetxr/S94sVkH4LcQ0i7wrETyN9BpqV4MSvrdrW8exfoHdrehjsScEmHNo0zLzNzIZXxsbgO0Iap9LMVI9o3Bv6iX6eQaF5MVJzvoqo+oMC78X+kUHdRXchGENI2Fnggc4qi/8iPpGTeprYbqscXQE3daq2B5FoN3OWFu1+b7gJsp4IAeDq9ClR8mhF2zLkDcylncmPY1EX4Cm39QJ0QaTawZuPNd9rwCNlP9cYVMEgf97R/wgOABJjq+WX37YOUSl6pQ5obJUYoOrZQuKYJ8jqkaq3N/RLlK5655ynCe1rxdH+J9HIg5WrVYUAv+wCy/TWCW5tXnN3U7LXS2JOAQCtWF/nSPw78aHelGkIxVHxLDnOU+ColEAxP+Cd5RoBEey6WQD+qK2ta/Gd8sz/p1CRk+Y4qohp7MIoCeYBK7AzrVsRI3wSXX2rihXyidszd7kUtIAWJ/cRZm8XCGilzzuaizaQaq3yDNG+lXMLSlYBtbD2PvNC6Ra5qzJ+R/m9T2I1/G+Kfz/SalWChboT9XioPjWfw==
  template:
    metadata:
      name: keycloak-credentials
      namespace: staging
    type: Opaque
