apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      securityContext:
        fsGroup: 1001
      containers:
        - name: postgres
          image: bitnami/postgresql:latest
          securityContext:
            runAsUser: 1001
            allowPrivilegeEscalation: false
          env:
            - name: POSTGRESQL_USERNAME
              value: keycloak
            - name: POSTGRESQL_PASSWORD
              value: keycloak
            - name: POSTGRESQL_DATABASE
              value: keycloak
            - name: POSTGRESQL_POSTGRES_PASSWORD
              value: rootpassword
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-data
              mountPath: /bitnami/postgresql/data
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: db-pvc-volume