image: eclipse-temurin:21-jdk-alpine

variables:
  GRADLE_USER_HOME: "$CI_PROJECT_DIR/.gradle"

cache:
  key: "$CI_COMMIT_REF_SLUG"
  paths:
    - .gradle/wrapper/
    - .gradle/caches/
    - build/

before_script:
  - export GRADLE_USER_HOME

build:
  stage: build
  script:
    - ./gradlew --build-cache assemble

test:
  stage: test
  script:
    - ./gradlew check
publish:
  stage: publish
  script:
    - ./gradlew publish