
plugins {
	id 'java'
}
java {
	sourceCompatibility = JavaVersion.toVersion(findProperty('javaVersion') ?: 21)
	targetCompatibility = JavaVersion.toVersion(findProperty('javaVersion') ?: 21)
}
allprojects {
	repositories {
		mavenCentral()
	}

}

configurations {
	compileOnly {
		extendsFrom annotationProcessor
	}
}
