apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: permis360-platform-components
spec:
  type: url
  targets:
    - https://github.com/e2rabi/permis360/blob/dev/modules/appointment-service/catalog-info.yaml
    - https://github.com/e2rabi/permis360/blob/dev/modules/document-service/catalog-info.yaml
    - https://github.com/e2rabi/permis360/blob/dev/modules/school-service/catalog-info.yaml