services:
  keycloak-service:
    image: keycloak/keycloak:25.0.1
    command: start-dev --metrics-enabled=true --http-enabled=true
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HTTP_ENABLED: "true"
      KC_HEALTH_ENABLED: "true"
      KC_HOSTNAME_STRICT: "false"
      KC_HOSTNAME_STRICT_HTTPS: "false"
      KC_METRICS_ENABLED: true
      KC_PROXY: edge
      KC_HOSTNAME: 194.163.129.95
      KC_PROXY_HEADERS: "xforwarded"
      KC_LOG_LEVEL: DEBUG
    ports:
      - "8080:8080"
    volumes:
      - keycloak_data:/opt/keycloak/data
    healthcheck:
      test: ["CMD-SHELL", "echo > /dev/tcp/localhost/8080"]
      interval: 10s
      timeout: 5s
      retries: 30
      start_period: 40s
    restart: unless-stopped
  minio-service:
    image: minio/minio:RELEASE.2025-04-08T15-41-24Z
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      MINIO_PROMETHEUS_AUTH_TYPE: public
      MINIO_PROMETHEUS_URL: http://minio-service:9000
    ports:
      - "9000:9000" # MinIO API port
      - "9001:9001" # MinIO Console port
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9000/minio/health/live || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
    restart: unless-stopped
  redis-service:
    image: redis:7.0.5
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    restart: unless-stopped
  redis-exporter:
    image: oliver006/redis_exporter:latest
    environment:
      REDIS_ADDR: redis://redis-service:6379
    ports:
      - "9121:9121"
    depends_on:
      - redis-service
    restart: unless-stopped
  prometheus-service:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./infrastructures/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    depends_on:
      keycloak-service:
        condition: service_started
      minio-service:
        condition: service_started
      redis-exporter:
        condition: service_started
    restart: unless-stopped
  document-service:
    #build: ./modules/document-service
    image: e2rabi11/document-service:latest
    container_name: document-service
    environment:
      SPRING_PROFILES_ACTIVE: staging
      OTEL_SDK_DISABLED: false
      OTEL_SERVICE_NAME: document-service
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4317
      OTEL_EXPORTER_OTLP_PROTOCOL: grpc
      OTEL_TRACES_EXPORTER: otlp
      OTEL_METRICS_EXPORTER: none
      OTEL_LOGS_EXPORTER: otlp
      MINIO-ACCESS-KEY: 62C1KWw7NXI7irZl50AN
      MINIO-SECRET-KEY: HOHVs2yqCqdikVOppeOfNK3UgWccSuQ99W4HTB1L
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-service:8080/eureka/
      EUREKA-SERVER-URL: http://eureka-service:8080
    ports:
      - "8009:8080"
    depends_on:
      keycloak-service:
        condition: service_healthy
      eureka-service:
        condition: service_started
  school-service:
    #build: ./modules/school-service
    image: e2rabi11/school-service:latest
    container_name: school-service
    environment:
      SPRING_PROFILES_ACTIVE: staging
      OTEL_SDK_DISABLED: false
      OTEL_SERVICE_NAME: school-service
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4317
      OTEL_EXPORTER_OTLP_PROTOCOL: grpc
      OTEL_TRACES_EXPORTER: otlp
      OTEL_METRICS_EXPORTER: none
      OTEL_LOGS_EXPORTER: otlp
    ports:
      - "8010:8080"
    depends_on:
      keycloak-service:
        condition: service_healthy
  eureka-service:
    #build: ./infrastructures/eureka-server
    image: e2rabi11/eureka-service:latest
    container_name: eureka-service
    environment:
      SPRING_PROFILES_ACTIVE: staging
      OTEL_SDK_DISABLED: false
      OTEL_SERVICE_NAME: eureka-service
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4317
      OTEL_EXPORTER_OTLP_PROTOCOL: grpc
      OTEL_TRACES_EXPORTER: otlp
      OTEL_METRICS_EXPORTER: none
      OTEL_LOGS_EXPORTER: otlp
    ports:
      - "8761:8080"
    depends_on:
      keycloak-service:
        condition: service_healthy
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.101.0
    container_name: otel-collector
    command: ["--config=/etc/otelcol-contrib/config.yaml"]
    volumes:
      - ./infrastructures/otel-collector-config.yaml:/etc/otelcol-contrib/config.yaml
    ports:
      - "4317:4317"   # OTLP gRPC
      - "4318:4318"   # OTLP HTTP
    environment:
      COLLECTOR_OTLP_ENABLED: "true"
    depends_on:
      jaeger:
        condition: service_started
    restart: unless-stopped
  jaeger:
      image: jaegertracing/all-in-one:1.67.0
      container_name: jaeger
      ports:
        - "16686:16686" # UI
        - "14250:14250"
      restart: unless-stopped
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.1.0
    container_name: elasticsearch
    environment:
      discovery.type: single-node
      xpack.security.enabled: false
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data
  kibana:
    image: docker.elastic.co/kibana/kibana:9.1.0
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    volumes:
      - kibana_data:/usr/share/kibana/data
    depends_on:
      - elasticsearch
  postgres-service:
    image: postgres:17
    container_name: postgres
    environment:
      POSTGRES_DB: autoecole_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d autoecole_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
volumes:
  postgres_data:
  keycloak_data:
  minio_data:
  redis_data:
  prometheus_data:
  es_data:
  kibana_data: