pluginManagement {
    repositories {
        gradlePluginPortal()
        mavenCentral()
        maven {
            name = "GitLabPackages"
            url = uri("https://gitlab.com/api/v4/projects/75932669/packages/maven")
            credentials(HttpHeaderCredentials) {
                name = "Deploy-Token"
                value = System.getenv('GITLAB_TOKEN')
            }
            authentication {
                header(HttpHeaderAuthentication)
            }
        }
    }
}
rootProject.name = 'siyaka-pro'
include "plugins:custom-gradle-bom"
include "plugins:custom-gradle-plugin"
include "modules:customer-service"
include "modules:appointment-service"
include "modules:school-service"
include "modules:learning-service"
include "modules:payment-service"
include "modules:notification-service"
//includeBuild('plugins/custom-gradle-plugin')


