

keycloak-issuer-uri = http://194.163.129.95:8080/realms/api-core
keycloak-client-id=siyaka-client
keycloak-client-secret=isCfVzXZDfsNiyo5HiKpfkFlg7bV3cGS


postgres-url=jdbc:postgresql://194.163.129.95:5432/autoecole_db?currentSchema=appointment
postgres-username=admin
postgres-password=admin
postgres-schema-name=appointment

eureka-server-url=http://eureka-service:8080/eureka/