

keycloak-issuer-uri = http://keycloak-service/auth/realms/api-core
keycloak-client-id=siyaka-client
keycloak-client-secret=tH3KulwiHm2BUuOP1Dyy9JMlYRRvSC97


postgres-url=jdbc:postgresql://postgres-service:5432/autoecole_db?currentSchema=document
postgres-username=
postgres-password=
postgres-schema-name=document

minio-url=http://minio-service:9000
minio-access-key=07MqlRmJrltQ6cOSISfI
minio-secret-key=iouRIBY25Eq0TJdak85IBU54gKf2IccaZbdAuGQT
minio-bucket=auto-ecole