

keycloak-issuer-uri = http://194.163.129.95:8080/realms/api-core
keycloak-client-id=siyaka-client
keycloak-client-secret=isCfVzXZDfsNiyo5HiKpfkFlg7bV3cGS


postgres-url=jdbc:postgresql://194.163.129.95:5432/autoecole_db?currentSchema=document
postgres-username=admin
postgres-password=admin
postgres-schema-name=document

minio-url=http://194.163.129.95:9000
minio-access-key=ezPgpUTY5QuchUxYojG4
minio-secret-key=G2vduEiNB4gdpYQYYjdQwnaZmKWz1BSKO8pcgX08
minio-bucket=my-bucket
eureka-server-url=http://194.163.129.95:8761