
spring:
  docker:
      compose:
        enabled: false
        file: /Users/errabi/Desktop/projects/autoecole-platform/docker-compose.yaml
  application:
    name: document-service
  security:
    oauth2:
      resourceserver: # Resource Server Configuration used to validate incoming JWT tokens
        jwt:
          issuer-uri: http://keycloak-service:8080/realms/api-core
      client: # OAuth2 Client Configuration used for outgoing requests
        registration:
          keycloak:
            client-id: siyaka-client
            scope: openid,profile,email
            client-secret: isCfVzXZDfsNiyo5HiKpfkFlg7bV3cGS
            authorization-grant-type: client_credentials
        provider:
          keycloak:
            issuer-uri: http://keycloak-service:8080/realms/api-core
  # Database Configuration
  datasource:
    url: jdbc:postgresql://postgres-service:5432/autoecole_db?currentSchema=document
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        default_schema: document
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    default-schema: document
    schemas: document
    locations: classpath:db/migration
  h2:
    console:
      enabled: false
      path: /h2-console
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui/index.html

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: document-service
      environment: staging

minio :
  bucket: my-bucket
  accessKey: ezPgpUTY5QuchUxYojG4
  secretKey: G2vduEiNB4gdpYQYYjdQwnaZmKWz1BSKO8pcgX08
  endpoint: http://minio-service:9000
server:
  port: 8080
