apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-service
  namespace: staging
  labels:
    app: api-gateway-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway-service
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
        app: api-gateway-service
        app-type: backend
    spec:
      automountServiceAccountToken: false
      containers:
        - name: api-gateway-service
          image: e2rabi11/api-gateway:1.3.2
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "1000m"
              memory: "1Gi"
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "staging"
            - name: OTEL_SDK_DISABLED
              value: "false"
            - name: OTEL_SERVICE_NAME
              value: "api-gateway-service"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://otel-collector-service:4317"
            - name: OTEL_EXPORTER_OTLP_PROTOCOL
              value: "grpc"
            - name: OTEL_TRACES_EXPORTER
              value: "otlp"
            - name: OTEL_METRICS_EXPORTER
              value: "none"
            - name: OTEL_LOGS_EXPORTER
              value: "otlp"