apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana-service
  namespace: staging
  labels:
    app: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
      labels:
        app: kibana
    spec:
      automountServiceAccountToken: false
      containers:
        - name: kibana
          image: docker.elastic.co/kibana/kibana:9.1.0
          ports:
            - containerPort: 5601
          env:
            - name: ELASTICSEARCH_HOSTS
              value: "http://elasticsearch-service:9200"
            - name: SERVER_BASEPATH
              value: "/kibana"
            - name: SERVER_REWRITEBASEPATH
              value: "true"
          volumeMounts:
            - name: kibana-data
              mountPath: /usr/share/kibana/data
      volumes:
        - name: kibana-data
          persistentVolumeClaim:
            claimName: kibana-data-pvc