apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-collector-service
  namespace: staging
  labels:
    app: otel-collector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: otel-collector
  template:
    metadata:
      labels:
        sidecar.istio.io/inject: "false"
        app: otel-collector
    spec:
      containers:
        - name: otel-collector
          image: otel/opentelemetry-collector-contrib:0.101.0
          args: [ "--config=/etc/otelcol-contrib/config.yaml" ]
          ports:
            - name: otlp-grpc
              containerPort: 4317
              protocol: TCP
            - name: otlp-http
              containerPort: 4318
              protocol: TCP
          env:
            - name: COLLECTOR_OTLP_ENABLED
              value: "true"
          volumeMounts:
            - name: config-volume
              mountPath: /etc/otelcol-contrib/config.yaml
              subPath: config.yaml
      volumes:
        - name: config-volume
          configMap:
            name: otel-collector-config
