apiVersion: apps/v1
kind: Deployment
metadata:
  name: school-service
  namespace: staging
  labels:
    app: school-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: school-service
  template:
    metadata:
      labels:
        app: school-service
    spec:
      containers:
        - name: school-service
          image: e2rabi11/school-service:1.3.1
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "staging"
            - name: OTEL_SDK_DISABLED
              value: "true"
            - name: OTEL_SERVICE_NAME
              value: "school-service"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://otel-collector:4317"
            - name: OTEL_EXPORTER_OTLP_PROTOCOL
              value: "grpc"
            - name: OTEL_TRACES_EXPORTER
              value: "otlp"
            - name: OTEL_METRICS_EXPORTER
              value: "none"
            - name: OTEL_LOGS_EXPORTER
              value: "otlp"
