apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: appointment-service
spec:
  type: service
  lifecycle: production
  owner: team-platform
  system: permis360-platform
  tags:
    - backend
    - java
    - spring-boot
    - microservices