apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: school-service
spec:
  type: service
  lifecycle: dev
  owner: team-platform
  system: permis360-backend
  dependsOn:
    - component:document-service
  tags:
    - backend
    - java
    - spring-boot
    - microservices