apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: school-service
  annotations:
    backstage.io/techdocs-ref: url:https://github.com/e2rabi/permis360/blob/dev/README.md
spec:
  type: service
  lifecycle: dev
  owner: team-platform
  system: permis360-backend
  dependsOn:
    - component:document-service
  tags:
    - backend
    - java
    - spring-boot
    - microservices