apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: school-app-service-monitor
  namespace: dev
  labels:
    release: prometheus
spec:
  jobLabel: job
  selector:
    matchLabels:
      app: school-service
  endpoints:
    - port: http
      path: /actuator/prometheus
      interval: 15s
      scheme: http
