plugins {
	id 'custom-gradle-plugin' version '2.3.4'
}


dependencies {
	annotationProcessor platform(project(':plugins:custom-gradle-bom'))
	implementation platform(project(':plugins:custom-gradle-bom'))

	implementation(project(":sdk:sdk-common")) {
		exclude group: 'org.springframework.boot', module: 'spring-boot-starter-data-jpa'
		exclude group: 'org.springframework.boot', module: 'spring-boot-starter-jdbc'
	}

	implementation 'org.springframework.boot:spring-boot-starter-actuator'
	implementation 'org.springframework.cloud:spring-cloud-starter'
	implementation 'org.springframework.cloud:spring-cloud-starter-netflix-eureka-client'
	implementation 'org.springframework.cloud:spring-cloud-starter-loadbalancer'
	implementation("org.springframework.cloud:spring-cloud-starter-gateway-server-webflux")
	implementation 'org.springframework.boot:spring-boot-starter-webflux'
	implementation 'org.springdoc:springdoc-openapi-starter-webflux-ui'
	implementation 'io.micrometer:micrometer-registry-prometheus'


	// Test
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
	// Lombok
	compileOnly 'org.projectlombok:lombok'
	annotationProcessor 'org.projectlombok:lombok'
	// MapStruct
	implementation 'org.mapstruct:mapstruct'
	annotationProcessor 'org.mapstruct:mapstruct-processor'
	// Lombok + MapStruct binding
	annotationProcessor 'org.projectlombok:lombok-mapstruct-binding'

}

bootJar {
	archiveFileName = 'app.jar'
}