apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: school-service-dr
  namespace: staging
spec:
  host: school-service
  subsets:
    - name: v1
      labels:
        app: school-service
      trafficPolicy:
        connectionPool:
          http:
            http1MaxPendingRequests: 10
            maxRequestsPerConnection: 10
          tcp:
            maxConnections: 2
        outlierDetection:
          consecutive5xxErrors: 5
          interval: 5s
          baseEjectionTime: 30s
          maxEjectionPercent: 50