plugins {
    id 'java'
    id 'java-library'
}

dependencies {
    implementation platform(project(':plugins:custom-gradle-bom'))
    implementation 'jakarta.validation:jakarta.validation-api'
    implementation 'org.springdoc:springdoc-openapi-ui'
    implementation 'com.fasterxml.jackson.core:jackson-databind'
}