plugins {
    id 'java-platform'
}

javaPlatform {
    allowDependencies()
}
dependencies {
    constraints {
        api 'org.springframework.boot:spring-boot-starter-webflux:4.0.5'
        api 'org.springframework.boot:spring-boot-starter-web:4.0.5'
        api 'org.springframework.boot:spring-boot-starter-test:4.0.5'
        api 'org.springframework.boot:spring-boot-starter-data-jpa:4.0.5'
        api 'org.springframework.boot:spring-boot-starter-actuator:4.0.5'
        api 'org.springframework.boot:spring-boot-starter-validation:4.0.5'
        api 'org.springframework.boot:spring-boot-starter-oauth2-client:4.0.5'
        api 'org.springframework.boot:spring-boot-starter-cache:4.0.5'
        api  'org.springframework.boot:spring-boot-starter-data-redis:4.0.5'
        api 'org.springframework.boot:spring-boot-starter-oauth2-resource-server:4.0.5'
        api 'org.springframework.boot:spring-boot-devtools:4.0.5'
        api 'io.micrometer:micrometer-registry-prometheus:1.16.0'
        api 'software.amazon.awssdk:s3:2.20.0'
        api 'org.springframework.cloud:spring-cloud-starter-openfeign:5.0.1'
        api 'org.springframework.cloud:spring-cloud-starter-circuitbreaker-resilience4j:5.0.1'
        api 'org.springframework.cloud:spring-cloud-starter-netflix-eureka-server:5.0.1'
        api 'org.springframework.boot:spring-boot-starter-security:4.0.5'
        api 'org.springframework.boot:spring-boot-docker-compose:4.0.5'
        api 'org.keycloak:keycloak-admin-client:26.0.9'
        api 'org.postgresql:postgresql:42.7.11'
        api 'org.jspecify:jspecify:1.0.0'




        api 'org.mapstruct:mapstruct-processor:1.5.5.Final'
        api 'ma.errabi:custom-gradle-plugin:2.3.2'
        api 'org.projectlombok:lombok:1.18.40'
        api 'org.mapstruct:mapstruct:1.5.5.Final'
        api 'org.projectlombok:lombok-mapstruct-binding:0.2.0'
        api 'com.h2database:h2:2.2.220'
        api 'org.springframework.boot:spring-boot-starter-flyway:4.0.5'
        api 'jakarta.validation:jakarta.validation-api:3.0.2'
        api 'com.fasterxml.jackson.core:jackson-databind:2.15.2'
        api 'org.springdoc:springdoc-openapi-starter-webmvc-ui:3.0.3'
        api 'org.springdoc:springdoc-openapi-ui:1.6.15'
        api 'org.flywaydb:flyway-database-postgresql:11.14.1'
        api 'com.tngtech.archunit:archunit-junit5:1.4.2'
        api 'org.springframework.boot:spring-boot-devtools:4.0.5'

    }
}
