plugins {
    id 'java'
    id 'java-gradle-plugin'
    id 'maven-publish'
    id 'com.google.cloud.tools.jib' version '3.4.0'
}
jib {
    from {
        image = 'eclipse-temurin:21-jre'
    }
}
group = 'ma.errabi'
version = '1.0.4'
repositories {
    gradlePluginPortal()
    mavenCentral()
}

dependencies {
    implementation("org.springframework.boot:spring-boot-gradle-plugin:3.5.7")
    implementation("com.google.cloud.tools:jib-gradle-plugin:3.4.0")
}
gradlePlugin {
    plugins {
        bootAndDependencyManagement {
            id = 'ma.errabi.build-plugin'
            implementationClass = 'ma.errabi.BootAndDependencyManagementPlugin'
            displayName = 'Errabi build Plugin'
            description = 'A simple custom Gradle plugin that build project.'
        }
    }
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java
        }
    }
    repositories {
        maven {
            name = "GitLabPackages"
            url = uri("https://gitlab.com/api/v4/projects/75932669/packages/maven")
            credentials(HttpHeaderCredentials) {
                name = "Deploy-Token"
                value = System.getenv('GITLAB_TOKEN')
            }
            authentication {
                header(HttpHeaderAuthentication)
            }
        }
    }
}

