apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: permis360-backend
  description: Auto-Ecole backend platform
  tags:
    - backend
    - java
    - spring-boot
    - microservices
spec:
  owner: team-platform
  lifecycle: dev
  domain: permis360-ma