apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: permis360-platform
  description: Auto-Ecole backend platform
  tags:
    - backend
    - java
    - spring-boot
    - microservices
spec:
  owner: team-platform
  lifecycle: production
  domain: permis360-ma