apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
  namespace: staging
  labels:
    app: otel-collector
data:
  config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:

    processors:
      batch:

    exporters:
      otlp:
        endpoint: jaeger-service:4317
        tls:
          insecure: true
      elasticsearch:
        endpoints:
          - http://elasticsearch-service:9200
        logs_index: otel-logs
        mapping:
          mode: none

    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlp]
        logs:
          receivers: [otlp]
          processors: [batch]
          exporters: [elasticsearch]