apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: staging
  labels:
    name: prometheus-config
data:
  prometheus.yml: |-
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: "document-service"
        metrics_path: "/document-service/actuator/prometheus"
        static_configs:
          - targets: ["document-service:8080"]

      - job_name: "school-service"
        metrics_path: "/school-service/actuator/prometheus"
        static_configs:
          - targets: ["school-service:8080"]

      - job_name: "api-gateway-service"
        metrics_path: "/api/actuator/prometheus"
        static_configs:
          - targets: ["api-gateway-service:8080"]

      - job_name: 'prometheus'
        metrics_path: "/prometheus/metrics"
        static_configs:
          - targets: ['prometheus-service:9090']

      - job_name: 'keycloak'
        metrics_path: /auth/metrics
        static_configs:
          - targets: ['keycloak-service:9000']

      - job_name: 'minio'
        metrics_path: /minio/v2/metrics/cluster
        static_configs:
          - targets: ['minio-service:9000']