plugins {
	id 'ma.errabi.build-plugin' version '1.0.0'
}

dependencies {
	annotationProcessor platform(project(':plugins:custom-gradle-bom'))
	implementation project(":sdk:sdk-common")
	implementation platform(project(':plugins:custom-gradle-bom'))

	implementation 'org.springframework.boot:spring-boot-starter-webflux'
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
	// Test
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

	// Lombok
	compileOnly 'org.projectlombok:lombok'
	annotationProcessor 'org.projectlombok:lombok'
	// MapStruct
	implementation 'org.mapstruct:mapstruct'
	annotationProcessor 'org.mapstruct:mapstruct-processor'
	// Lombok + MapStruct binding (required)
	annotationProcessor 'org.projectlombok:lombok-mapstruct-binding'
}
