plugins {
	id 'custom-gradle-plugin' version '2.3.1'
}

dependencies {
	annotationProcessor platform(project(':plugins:custom-gradle-bom'))
	implementation project(":sdk:sdk-common")
	implementation platform(project(':plugins:custom-gradle-bom'))
	implementation 'org.springframework.boot:spring-boot-starter-validation'
	implementation 'org.springframework.boot:spring-boot-starter-webflux'
	implementation 'org.springframework.boot:spring-boot-starter-web'
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
	implementation 'org.springframework.boot:spring-boot-starter-actuator'
	implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui'
	implementation 'io.micrometer:micrometer-registry-prometheus'
	implementation 'org.springframework.boot:spring-boot-starter-oauth2-client'
	implementation 'org.springframework.boot:spring-boot-starter-oauth2-resource-server'
	implementation 'org.springframework.security:spring-security-oauth2-jose'
	implementation 'org.springframework.cloud:spring-cloud-starter-openfeign'


	// Test
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
	// Lombok
	compileOnly 'org.projectlombok:lombok'
	annotationProcessor 'org.projectlombok:lombok'
	// MapStruct
	implementation 'org.mapstruct:mapstruct'
	annotationProcessor 'org.mapstruct:mapstruct-processor'
	// Lombok + MapStruct binding (required)
	annotationProcessor 'org.projectlombok:lombok-mapstruct-binding'
	// H2 Database (for tests)
	runtimeOnly("com.h2database:h2")
	implementation 'org.flywaydb:flyway-core'

}
