apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: staging
  labels:
    app: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      initContainers:
        - name: fix-permissions
          image: busybox
          command: [ "sh", "-c", "chown -R 1000:1000 /opt/keycloak/data" ]
          volumeMounts:
            - name: keycloak-data
              mountPath: /opt/keycloak/data
      containers:
        - name: keycloak
          image: keycloak/keycloak:25.0.1
          args: ["start-dev", "--metrics-enabled=true", "--http-enabled=true"]
          env:
            - name: KEYCLOAK_ADMIN
              valueFrom:
                  secretKeyRef:
                    name: keycloak-credentials
                    key: admin-user
            - name: KEYCLOAK_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-credentials
                  key: admin-password
            - name: KC_HTTP_ENABLED
              value: "true"
            - name: KC_HEALTH_ENABLED
              value: "true"
            - name: KC_HOSTNAME_STRICT
              value: "false"
            - name: KC_HOSTNAME_STRICT_HTTPS
              value: "false"
            - name: KC_METRICS_ENABLED
              value: "true"
            - name: KC_HOSTNAME_URL
              value: "http://13.140.173.47:8080"
            - name: KC_HOSTNAME_ADMIN_URL
              value: "http://13.140.173.47:8080"
          ports:
            - containerPort: 8080
              name: http
          volumeMounts:
            - name: keycloak-data
              mountPath: /opt/keycloak/data
      volumes:
        - name: keycloak-data
          persistentVolumeClaim:
            claimName: keycloak-pvc