server:
  port: 8443
  shutdown: graceful

spring:
  lifecycle:
    timeout-per-shutdown-phase: 30s
  main:
    web-application-type: reactive
  application:
    name: api-gateway-services
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      server:
        webflux:
          routes:
            - id: eureka-dashboard
              uri: http://localhost:8761
              predicates:
                - Path=/eureka
              filters:
                - RewritePath=/eureka, /
            - id: eureka-assets
              uri: http://localhost:8761
              predicates:
                # Catches /eureka/css, /eureka/js, /eureka/apps, etc.
                - Path=/eureka/**
            - id: document-service
              uri: lb://document-service:8099
              predicates:
                - Path=/documents/**
            - id: school-service
              uri: lb://school-service:8081
              predicates:
                - Path=/schools/**
          enabled: true

management:
  endpoints:
    web:
      exposure:
        include: gateway, health, info
  endpoint:
    gateway:
      enabled: true

  metrics:
    tags:
      application: api-gateway-service
      environment: dev

eureka:
  client:
    serviceUrl:
      defaultZone: "http://localhost:8761/eureka"
    initial-instance-info-replication-interval-seconds: 0
    registry-fetch-interval-seconds: 5

  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 5
    prefer-ip-address: true