server:
  port: 8080
  shutdown: graceful

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    urls:
      - name: School Service
        url: http://13.140.173.47/api/api/school-service/v3/api-docs
      - name: Document Service
        url: http://13.140.173.47/api/api/document-service/v3/api-docs
spring:
  webflux:
    base-path: /api
  lifecycle:
    timeout-per-shutdown-phase: 30s
  main:
    web-application-type: reactive
  application:
    name: api-gateway-services
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      server:
        webflux:
          routes:
          - id: document-service
            uri: http://document-service:8080
            predicates:
              - Path=/api/document-service/**
            filters:
              - StripPrefix=2

          - id: school-service
            uri: http://school-service:8080
            predicates:
              - Path=/api/school-service/**
            filters:
              - StripPrefix=2
          enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus,gateway,info
  endpoint:
    health:
      show-details: always
    gateway:
      enabled: true
  metrics:
    tags:
      application: api-gateway-service
      environment: staging
eureka:
  client:
    enabled: false