server:
  port: 8443
  shutdown: graceful

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    urls:
      - name: School Service
        url: /school/v3/api-docs
      - name: Document Service
        url: /document/v3/api-docs
spring:
  lifecycle:
    timeout-per-shutdown-phase: 30s
  main:
    web-application-type: reactive
  application:
    name: api-gateway-services
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      server:
        webflux:
          routes:
            - id: eureka-dashboard
              uri: lb://eureka-service:8080
              predicates:
                - Path=/eureka
              filters:
                - RewritePath=/eureka, /
            - id: eureka-assets
              uri: lb://eureka-service:8080
              predicates:
                # Catches /eureka/css, /eureka/js, /eureka/apps, etc.
                - Path=/eureka/**
            - id: document-service
              uri: lb://document-service:8080
              predicates:
                - Path=/documents/**
            - id: school-service
              uri: lb://school-service:8080
              predicates:
                - Path=/schools/**
            - id: school-service-swagger
              uri: lb://school-service
              predicates:
                - Path=/school/**
              filters:
                - StripPrefix=1
            - id: document-service-swagger
              uri: lb://document-service
              predicates:
                - Path=/document/**
              filters:
                - StripPrefix=1
          enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus,gateway,info
  endpoint:
    health:
      show-details: always
    gateway:
      enabled: true
  metrics:
    tags:
      application: api-gateway-service
      environment: staging
eureka:
  client:
    serviceUrl:
      defaultZone: ${eureka-server-url}
    initial-instance-info-replication-interval-seconds: 0
    registry-fetch-interval-seconds: 5
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 5
    prefer-ip-address: true