apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: dockerhub-secret
  namespace: dev
spec:
  encryptedData:
    .dockerconfigjson: AgCO1RN5EUOg4kqxiCv5Xq3kWxjXfuvZNH+jkXPmKofbBToZHyQxMh7Wg8jQbo8091o90Cxge56bZaitMoQh9964q2ktju0Ogsz+8D+zRPZW6zE7//f8InXnpa6DYQflh+aHMqLxhAS2A8k67vAgjnGF4UlMdNZQV0y6iWqSnB50aOXpgbui5thdgOey290of99MgTBgMVxPEhlzaTOUqauvxGhgIymtujueEZJ9MlHhqY3+uDMzk17KcD53Z7XxWbSXzaHj2Zl3Ol9I03N8i14KUjCso81qn1EJg7j7LpejBO/trlv7MkWwcIRVvOkbx69ZUvy6C1WB0hN+E4GXp2R0apQ6wUwYmqgXhlKCHMwGf+XCRvwHUmIVg0Hlhb0oyZGdsGjlHrzhdb3EgcTJoCwcPlDz1x1d3I5sJ3CaqPG+lQFvyiTFeVzkx/CSV9OASIIhgnxFjTAaE+LH/5qMOrv0lyK7y/Z2eIY2AZ2eed63ptulQDDVFietUHGZK3R1e6lajaU6UBC/0hiM9ywLdi6t3Wiye2T+Al/2STBrq7mqc6dPw5HaaPBmFB8HboUfpu8djKc3j6ycVMkEXPDfHkcy31AJyKmGkEKVTFP4PxvwRubEUXfkUWuOQ8Oa5Q494D+Cts3ZJzfFCeYxCmLIRzwsKZ7/RgqxYAArU0R9PyIO2n7lD+5QKG8vdyZfgePqjzKekF5EyIymOT0Ab8zpwD/PYYD6SIr4SFYfJ3w596TSTkiebk87lnsbQI/ilsmo/V7CAZZF5EAbtBYdsWM29jWTdrb9lbOdqkCoVk8MdK4hW5nkEoaOyh6mVyPWlV7VxNGv3xKyy+f3YUooP0MU7kaeM4FESbxV2ACqD/eM726AhE9THt+T2orpdMwfwS1vuy4riAnYAY3+qutIJj4kwbSZsOlny7Uq3ZqJlEawYn/WIUPjNBE3AdkDp5acDpo1Iz/qIqikI9wK0bo3BQSb4iEBJFYsPaKswQGWYA==
  template:
    metadata:
      name: dockerhub-secret
      namespace: dev
    type: kubernetes.io/dockerconfigjson