apiVersion: v1
kind: LimitRange
metadata:
  name: cpu-resource-constraint
  namespace: dev
spec:
  limits:
    - default:
        cpu: 500m
        memory: 250Mi
      defaultRequest:
        cpu: 500m
        memory: 250Mi
      max:
        cpu: 500m
        memory: 250Mi
      min:
        cpu: 250m
        memory: 250Mi
      type: Container
