apiVersion: apps/v1
kind: Deployment
metadata:
  name: school-service-deployment
  namespace: dev
  annotations:
    argo-cd.argoproj.io/sync-wave: "3"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: school-service
  template:
    metadata:
      labels:
        type: backend
        app: school-service
    spec:
      containers:
        - image: e2rabi11/school-service:0.1.0-SNAPSHOT
          name: school-service
          ports:
            - containerPort: 8081
      imagePullSecrets:
        - name: dockerhub-secret